[package]
name = "why-do-i-really-like-ncurses"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
ascii = "1.1.0"
ncursesw = "0.6.4"
termion = "2.0.1"
